site_name: File Formats in Science
site_url: https://mydomain.org/mysite
repo_url: https://github.com/squidfunk/mkdocs-material
theme:
  features:
    - content.action.edit
  name: material
plugins:
  - git-revision-date-localized:
      enable_creation_date: true